// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5U52GTPagPRok2_Dt0dK1Bgw9SGSWTUk',
    appId: '1:971877145555:web:49e8fd03848c0e6ff3ad26',
    messagingSenderId: '971877145555',
    projectId: 'iot-air-alert',
    authDomain: 'iot-air-alert.firebaseapp.com',
    databaseURL: 'https://iot-air-alert-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-air-alert.firebasestorage.app',
    measurementId: 'G-F8LXLX1W37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp-19HZ5yP49vDF1ks7UFXUwwup_eSqVE',
    appId: '1:971877145555:android:50dc6bb52d942626f3ad26',
    messagingSenderId: '971877145555',
    projectId: 'iot-air-alert',
    databaseURL: 'https://iot-air-alert-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-air-alert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbBwTasQY_Iy-aGm4O4fpiTvnirybrwHc',
    appId: '1:971877145555:ios:8fe58d0fe8d656edf3ad26',
    messagingSenderId: '971877145555',
    projectId: 'iot-air-alert',
    databaseURL: 'https://iot-air-alert-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-air-alert.firebasestorage.app',
    iosBundleId: 'com.example.airQualityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbBwTasQY_Iy-aGm4O4fpiTvnirybrwHc',
    appId: '1:971877145555:ios:8fe58d0fe8d656edf3ad26',
    messagingSenderId: '971877145555',
    projectId: 'iot-air-alert',
    databaseURL: 'https://iot-air-alert-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-air-alert.firebasestorage.app',
    iosBundleId: 'com.example.airQualityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5U52GTPagPRok2_Dt0dK1Bgw9SGSWTUk',
    appId: '1:971877145555:web:cc85f7f0323ed8c9f3ad26',
    messagingSenderId: '971877145555',
    projectId: 'iot-air-alert',
    authDomain: 'iot-air-alert.firebaseapp.com',
    databaseURL: 'https://iot-air-alert-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-air-alert.firebasestorage.app',
    measurementId: 'G-7V6X6MRT9N',
  );
}
